# -*- coding: utf-8 -*-
"""
Created on Sat Jul  4 14:35:02 2020

@author: AsteriskAmpersand
"""
with open(r"E:\MHW-EFX-Template\EFX.bt","r", encoding='utf8') as inf:
    file = inf.read()
    for search,replace in [("Unkn_00","ExternReference"),
                            ("Unkn_02","FakePlane"),
                            ("Unkn_05","Dummy"),
                            ("Unkn_08","RandomFix"),
                            ("Unkn_09","Transform2D"),
                            ("Unkn_10","Billboard2D"),
                            ("Unkn_13","Blink"),
                            ("Unkn_14","LuminanceBleed"),
                            ("Unkn_15","EmitterShape2D"),
                            ("Unkn_16","Velocity2D"),
                            ("Unkn_18","Distortion"),
                            ("Unkn_19","MasterOnly"),
                            ("Unkn_22","TubeLight"),
                            ("Unkn_25","Shovel"),
                            ("Unkn_26","Layout"),
                            ("Unkn_27","FakeDoF"),
                            ("Unkn_28","RepeatArea"),
                            ("Unkn_29","LinkPartsVisible"),
                            ("Unkn_31","PtTrigger"),
                            ("Unkn_32","PathChain"),
                            ("Radial_Concentration","Homing"),
                            ("Unkn_34","EmitterShapeMesh"),
                            ("Unkn_36","SpawnByAngle"),
                            ("Unkn_37","CheckPureAttribute"),
                            ("Unkn_38","TonemapFilter"),
                            ("Unkn_39","ColorCorrectFilter"),
                            ("Basic_Transform","Transform3D"),
                            ("Limit_Transform","ParentOptions"),
                            ("Launcher_Property","Spawn"),
                            ("Life_Cycle","Life"),
                            ("Symmetric_Copy","EmitterShape3D"),
                            ("Momentum_Control","Velocity3D"),
                            ("Visible_Dist","FadeByDepth"),
                            ("Dds_Trace_Prop","RibbonBlade"),
                            ("Dds_Useage","Billboard3D"),
                            ("Loop_Play","ScaleAnim"),
                            ("Uvs_Useage","UVSequence"),
                            ("Transparent_Control","AlphaCorrection"),
                            ("Layer_Visibility","ShaderSettings"),
                            ("Color_Prop_Control","RgbFire"),
                            ("Mod3_Useage","Mesh"),
                            ("Self_Spin_Control","RotateAnim"),
                            ("Auras","PlEmissive"),
                            ("Follow","Guide"),
                            ("Lightning","Lightning"),
                            ("Emissive_Rim","ParentEmissive"),
                            ("External_Bind","PtCollision"),
                            ("Albedo_Blend","PlSnow"),
                            ("EFX_Behaviors","PtBehavior"),
                            ("Texture","Material"),
                            ("Dds_Useage_Alt","Plane"),
                            ("Cubemap","RgbWater"),
                            ("CM_Map","Turbulence"),
                            ("Unkn_01","FadeByEmitterAngle"),
                            ("Trail_Physics","Ribbon"),
                            ("Randomized_Oscillations","Noise"),
                            ("Texture_Animation","UVControl"),
                            ("Unkn_07","FadeByAngle"),
                            ("Unkn_11","EmitterBoundary"),
                            ("Relationship","PtLife"),
                            ("Catenary_Physics","StrainRibbon"),
                            ("Collision","ScreenSpaceCollision"),
                            ("Beam_Collision","RayCast"),
                            ("Unkn_40","SpawnByOcclusion"),
                            ("Unkn_41","FadeByOcclusion"),
                            ("Unkn_42","ParentSnow"),
                            ("Unkn_43","OtomoSnow"),
                            ("Unkn_44","ParentMaterial"),
                            ("UN_PREFIX_0","ExternTransform3D"),
                            ("UN_PREFIX_5","ExternMesh"),
                            ("UN_PREFIX_9","ExternPlEmissive"),
                            ("UN_PREFIX_13","ExternPtBehavior"),
                            ("UN_PREFIX_14","ExternRgbWater"),
                            ("UN_PREFIX_1","ExternVelocity3D"),
                            ("UN_PREFIX_7","ExternEmitterShape3D"),
                            ("UN_PREFIX_15","ExternParentEmissive"),
                            ("UN_PREFIX_4","ExternSpawn"),
                            ("UN_PREFIX_3","ExternRgbFire"),
                            ("UN_PREFIX_11","ExternRibbon"),
                            ("UN_PREFIX_16","ExternRotateAnim"),
                            ("UN_PREFIX_6","ExternBillboard3D"),
                            ("UN_PREFIX_2","ExternScaleAnim"),
                            ("UN_PREFIX_10","ExternLife"),
                            ("UN_PREFIX_8","ExternUVSequence"),
                            ("UN_PREFIX_17","ExternPlane"),
                            ("UN_PREFIX_12","ExternPlSnow"),
                            ("UN_PREFIX","Extern"),
                            ("S_P_1","UnitBoundary"),
                            ("S_P_2","RenderTarget"),
                            ("S_P_3","LayoutBank")]:
        file = file.replace(search.upper(),replace.upper())
        file = file.replace(search,replace)
        file = file.replace(search.lower(),replace.lower())
        
with open(r"E:\MHW-EFX-Template\EFX.bt","w", encoding='utf8') as outf:
    outf.write(file)